blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Ask a Question
    url: https://github.com/chrisnmorrison/revista-astro-blog-magazine/discussions/new?category=q-a
    about: Ask questions and discuss ideas with other community members
  - name: ðŸ“š Documentation
    url: https://github.com/chrisnmorrison/revista-astro-blog-magazine#readme
    about: Check the README and other documentation files
